# roles/mariadb/tasks/install/add-repo.yml
---

- name: Add official MariaDB repository (yum)
  template:
    src: etc_yum.repos.d_mariadb.repo.j2
    dest: /etc/yum.repos.d/MariaDB.repo
    mode: '0644'
  when: ansible_os_family != 'Debian'
  tags: mariadb

- name: Install gpg to add repokey (apt)
  package:
    name: gpg
    state: latest
  when: ansible_os_family == 'Debian'
  tags: mariadb

- name: Add official MariaDB repository (apt)
  deb822_repository:
    name: mariadb
    types: deb
    uris: "https://{{ mariadb_mirror }}/{{ mariadb_version }}/{{ ansible_distribution|lower }}"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    signed_by: https://mariadb.org/mariadb_release_signing_key.pgp
  when: ansible_os_family == 'Debian'
  tags: mariadb
